language: node_js
node_js:
  - '8'
  - '10'
cache:
  yarn: true
  directories:
    - 'node_modules'
    - 'packages/cldr-compiler/.cldr'
before_install:
  - npm install -g codecov yarn
install:
  - yarn
script:
  - yarn clean
  - yarn lint
  - yarn api
  - yarn test:codecov
after_success:
  - codecov

