name: Build and Test

on:
  push
  # branches:
  #  - actions
  #  - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Build
        run: |
          yarn
          yarn clean
          yarn lint
          yarn api

      - name: Test
        run: env TZ='America/New_York' yarn test:runtime
      # - name: Test
      #   run: |
      #     yarn test:codecov
      # - name: Upload Coverage
      #   uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
